"""
subprocess: used to run terminal commands via python
"""
import argparse
import os
import subprocess

from utils.generate_cfg_file import generate_files
from utils.get_nodes import (check_if_layer_called,
                             get_correct_block_via_func_name,
                             get_correct_block_via_layer)
from utils.treat_data import treat_metadata


def arguments():
    """
    Gets the paths and values inputed by the user
    """
    parser = argparse.ArgumentParser(
        prog="EGMV",
        description="Opens CFG files generated by CFGgrind",
    )
    parser.add_argument("-m", "--model_file", required=True,
                        help="Path to the input model file (CFG file)")
    parser.add_argument("-d", "--dot_file", required=False,
                        help="Path to output DOT file for graph visualization")
    parser.add_argument("-f", "--function_name", required=False,
                        help="Name of the function to focus on in the CFG")
    parser.add_argument("-c", "--convert", required=False,
                        help="If you want to just addapt the value to add metadata")
    args = parser.parse_args()

    return args

def get_model(model_path: str) -> list:
    """
    Get the model file path and returns a list where every line
    in the file is a list inside the model list
    """
    model = []
    try:
        with open(model_path, "r", encoding="utf8") as m:
            model = [line.strip() for line in m if line.strip()]
    except OSError as e:
        print(f"Error reading file: {e}")

    return model


def _run_model(file_path: str):
    """
    Runs a terminal command to start model explorer via python
    """
    model_run = f"model-explorer {file_path} --host=0.0.0.0 --extensions CFGgrid_ME"
    subprocess.run(model_run, shell=True, check=True)


def get_metadata(dot_path: str) -> list:
    """
    Will get the metadata via the dot file informed
    """
    dot_data = []
    if dot_path:
        try:
            with open(dot_path, "r", encoding="utf8") as j:
                dot_data = [line.strip() for line in j if line.strip()]
        except OSError as e:
            print(f"Error getting dot file: {e}")

    return dot_data


def main():
    """Get values"""
    args = arguments()
    
    model_path = args.model_file
    dot_path = args.dot_file
    function_name = args.function_name
    convert = args.convert

    if not function_name:
        function_name = "main"

    model = get_model(model_path)
    dot_data = get_metadata(dot_path)
    block = get_correct_block_via_func_name(model, function_name)
    connected_layer = check_if_layer_called(block)
    connected_block = get_correct_block_via_layer(model, connected_layer) if connected_layer else None
    treated_metadata = treat_metadata(dot_data)
    
    if connected_block:
        generate_files(block, connected_block, treated_metadata, function_name)
    else:
        generate_files(block, [], treated_metadata, function_name)
    
    folder_name = "generated_files"
    if not os.path.exists(folder_name):
        os.makedirs(folder_name)
    
    file_path = f"{folder_name}/{function_name}_addapted.cfg"
    if dot_path:
        file_path = f"{folder_name}/{function_name}_metadados.cfg"
   
    if convert:
        print(f"Addapted file with metadata generated in {file_path}")
    else:
        _run_model(file_path)


if __name__ == "__main__":
    main()
