"""
subprocess: used to run terminal commands via python
"""
import os
import subprocess
import argparse
from utils.generate_cfg_file import (
    generate_files,
)
from utils.treat_data import treat_metadata


def arguments():
    """
    Gets the paths and values inputed by the user
    """
    parser = argparse.ArgumentParser(
        prog="EGMV",
        description="Opens CFG files generated by CFGgrind",
    )
    parser.add_argument("-m", "--model_file", required=True)
    parser.add_argument("-d", "--dot_file", required=False)
    parser.add_argument("-f", "--function_name", required=False)
    args = parser.parse_args()

    model_file = args.model_file
    dot_file = args.dot_file
    function_name = args.function_name

    return model_file, dot_file, function_name


def get_model(model_path: str) -> list:
    """
    Get the model file path and returns a list where every line
    in the file is a list inside the model list
    """
    model = []
    try:
        with open(model_path, "r", encoding="utf8") as m:
            model = [line.strip() for line in m if line.strip()]
    except OSError as e:
        print(f"Error reading file: {e}")

    return model


def get_correct_block(model: list, function_name: str):
    """
    Based on the list with the lines of the CFG in model,
    this function gets the specific block informed by the user
    via function_name
    """

    block = []
    init_block = -1
    finish_block = -1
    correct_start = "::" + function_name
    for i, line in enumerate(model):
        if (line.startswith("[cfg") 
        and function_name in line 
        and correct_start in line):
            init_block = i
            break

    for i in range(init_block + 1, len(model)):
        if model[i].startswith("[cfg"):
            break

        finish_block = i

    block = model[init_block : finish_block + 1]
    return block


def _run_model(file_path: str):
    """
    Runs a terminal command to start model explorer via python
    """
    model_run = f"model-explorer {file_path} --host=0.0.0.0 --extensions CFGgrid_ME"
    subprocess.run(model_run, shell=True, check=True)


def get_metadata(dot_path: str) -> list:
    """
    Will get the metadata via the dot file informed
    """
    dot_data = []
    if dot_path:
        try:
            with open(dot_path, "r", encoding="utf8") as j:
                dot_data = [line.strip() for line in j if line.strip()]
        except OSError as e:
            print(f"Error getting dot file: {e}")

    return dot_data


def main():
    """Get values"""

    model_path, dot_path, function_name = arguments()

    if not function_name:
        function_name = "main"

    model = get_model(model_path)
    dot_data = get_metadata(dot_path)
    block = get_correct_block(model, function_name)
    treated_metadata = treat_metadata(dot_data)
    generate_files(block, treated_metadata, function_name)
    folder_name = "generated_files"
    file_path = f"{folder_name}/{function_name}_addapted.cfg"
    
    if not os.path.exists(folder_name):
        os.makedirs(folder_name)
    
    if dot_path:
        file_path = f"{folder_name}/{function_name}_metadados.cfg"
    else:
        file_path = f"{folder_name}/{function_name}_addapted.cfg"
    _run_model(file_path)


if __name__ == "__main__":
    main()
