"""
subprocess: used to run terminal commands via python
"""
import argparse
import os
import subprocess
import sys

from utils.generate_cfg_file import generate_files
from utils.get_nodes import get_correct_block_via_func_name
from utils.treat_data import treat_metadata


def arguments():
    """
    Gets the paths and values inputed by the user
    """
    parser = argparse.ArgumentParser(
        prog="EGMV",
        description="Opens CFG files generated by CFGgrind",
    )
    parser.add_argument("-r", "--run", action="store_true",
                        help="Simply run Model Explorer")
    parser.add_argument("-c", "--convert",action="store_true",
                        help="Generate adapted file without opening Model Explorer")
    parser.add_argument("-g", "--graph_file",
                        help="Path to the input model file (CFG file)")
    parser.add_argument("-m", "--map_file",
                        help="Path to output map file for graph visualization")
    parser.add_argument("-f", "--function_name",
                        help="Name of the function to focus on in the CFG")
    args = parser.parse_args()

    return args

def get_model(model_path: str) -> list:
    """
    Get the model file path and returns a list where every line
    in the file is a list inside the model list
    """
    model = []
    try:
        with open(model_path, "r", encoding="utf8") as m:
            model = [line.strip() for line in m if line.strip()]
    except OSError as e:
        print(f"Error reading file: {e}")

    return model


def _run_model(file_path: str):
    """
    Runs a terminal command to start model explorer via python
    """
    model_run = f"model-explorer {file_path} --host=0.0.0.0 --extensions CFGgrid_ME"
    p = subprocess.Popen(model_run, shell=True)
    try:
        p.wait()
    except KeyboardInterrupt:
        print("\nKilling subprocess...")
        p.kill()
        p.wait()
        sys.exit(1)

def _run_only_model():
    """
    Runs a terminal command to start model explorer via python without any file
    """
    model_run = "model-explorer --host=0.0.0.0 --extensions CFGgrid_ME"
    p = subprocess.Popen(model_run, shell=True)
    try:
        p.wait()
    except KeyboardInterrupt:
        print("\nKilling subprocess...")
        p.kill()
        p.wait()
        sys.exit(1)

def get_metadata(map_path: str) -> list:
    """
    Will get the metadata via the MAP file informed
    """
    map_data = []
    if map_path:
        try:
            with open(map_path, "r", encoding="utf8") as j:
                map_data = [line.strip() for line in j if line.strip()]
        except OSError as e:
            print(f"Error getting MAP file: {e}")

    return map_data

def get_node_addresses(block: list) -> set:
    """Extracts the node start addresses from a CFG block."""
    addresses = set()
    for line in block:
        if line.startswith("[node"):
            addresses.add(line.split()[2])
    return addresses

def main():
    args = arguments()

    model_path = args.graph_file
    map_path = args.map_file
    function_name = args.function_name or "main"
    convert = args.convert
    run = args.run

    if run:
        _run_only_model()
        return

    folder_name = "generated_files"
    os.makedirs(folder_name, exist_ok=True)

    model = get_model(model_path)
    block = get_correct_block_via_func_name(model, function_name)

    treated_metadata = {}
    if map_path:
        map_data = get_metadata(map_path)
        node_addresses = get_node_addresses(block)
        treated_metadata = treat_metadata(map_data, node_addresses)

    generate_files(model, block, treated_metadata, function_name)

    file_suffix = "metadata" if map_path else "adapted"
    file_path = f"{folder_name}/{function_name}_{file_suffix}.cfg"

    if convert:
        print(f"Adapted file with metadata generated in {file_path}")
    else:
        _run_model(file_path)


if __name__ == "__main__":
    main()
